server:
  port: 8080

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: payment_service.infrastructure.event.PaymentCommand
        spring.json.trusted.packages: payment_service.infrastructure.event

services:
  payment:
    base-url: http://payment-service:8080/payments

payment:
  callback:
    url: http://payment-service:8080/payments

topics:
  payment:
    commands: payment-commands
    events: payment-events

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /
      path-mapping:
        health: internal-health
        prometheus: metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        shipping_payment_command_duration: true
      slo:
        shipping_payment_command_duration: 1s,2s,5s
